version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: starkiller2000turbo/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - backend_static:/backend_static/static/
      - media:/app/media
      - ../data/:/app/data
  frontend:
    image: starkiller2000turbo/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/staticfiles/static/
      - media:/media/
