# Generated by Django 4.2.3 on 2023-07-26 11:35

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[recipes.validators.validate_color],
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
