# Generated by Django 3.2.16 on 2023-08-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={
                'default_related_name': 'favorites',
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={
                'default_related_name': 'purchases',
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorites',
                to='recipes.recipe',
                verbose_name='рецепт',
            ),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='purchases',
                to='recipes.recipe',
                verbose_name='рецепт',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
    ]
