# Generated by Django 4.2.3 on 2023-07-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0003_recipe_recipetag_recipeingredient_recipe_ingredients_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="recipes/images/"),
        ),
    ]
