# Generated by Django 4.2.3 on 2023-07-27 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_recipeingredient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "default_related_name": "recipe_ingredients",
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецепта",
            },
        ),
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="amount",
            new_name="amounts",
        ),
    ]
