# Generated by Django 4.2.3 on 2023-07-27 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="amounts",
            new_name="amount",
        ),
    ]
