# Generated by Django 4.2.3 on 2023-07-27 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="amount",
        ),
    ]
