# Generated by Django 4.2.3 on 2023-07-28 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_favorited",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_in_shopping_cart",
        ),
    ]
