# Generated by Django 4.2.3 on 2023-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0015_alter_recipe_image_alter_recipe_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "recipe"), name="recipe_ingredient"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipetag",
            constraint=models.UniqueConstraint(
                fields=("tag", "recipe"), name="recipe_tag"
            ),
        ),
    ]
