# Generated by Django 4.2.3 on 2023-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0017_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="название"
            ),
        ),
    ]
