# Generated by Django 4.2.3 on 2023-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0018_alter_recipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                unique=True,
                upload_to="recipes/images/",
                verbose_name="картинка",
            ),
        ),
    ]
