# Generated by Django 4.2.4 on 2023-08-08 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0019_alter_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
    ]
