# Generated by Django 4.2.4 on 2023-08-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0020_remove_recipe_ingredients_remove_recipe_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецепта",
            },
        ),
        migrations.AlterModelOptions(
            name="recipetag",
            options={
                "verbose_name": "Тег рецепта",
                "verbose_name_plural": "Теги рецепта",
            },
        ),
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="recipe_ingredient",
        ),
        migrations.RemoveConstraint(
            model_name="recipetag",
            name="recipe_tag",
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="recipes.ingredient",
                verbose_name="ингредиент",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="recipes.recipe",
                verbose_name="рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="recipetag",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="recipes.recipe",
                verbose_name="рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="recipetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="recipes.tag",
                verbose_name="тег",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together={("ingredient", "recipe")},
        ),
        migrations.AlterUniqueTogether(
            name="recipetag",
            unique_together={("tag", "recipe")},
        ),
    ]
