# Generated by Django 3.2.16 on 2023-08-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followings',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
