# Generated by Django 4.2.3 on 2023-07-29 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0018_alter_recipe_name"),
        ("users", "0006_favorite_user_favorites_favorite_unique_user_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка",
                "verbose_name_plural": "Покупки",
            },
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_user_recipe",
        ),
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                related_name="selected",
                through="users.Favorite",
                to="recipes.recipe",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_user_favorite"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
                verbose_name="избранное",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="purchases",
            field=models.ManyToManyField(
                related_name="buyers",
                through="users.Purchase",
                to="recipes.recipe",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_user_purchase"
            ),
        ),
    ]
