# Generated by Django 4.2.4 on 2023-08-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_purchase_remove_favorite_unique_user_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="Galen", max_length=150, verbose_name="Имя"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="Marek", max_length=150, verbose_name="Фамилия"
            ),
            preserve_default=False,
        ),
    ]
