name: Main Foodgram Workflow

on:
  push:
    branches:
      main

env:
  POSTGRES_USER: foodgram_user
  POSTGRES_PASSWORD: foodgram_password
  POSTGRES_DB: foodgram
  DB_HOST: 127.0.0.1
  DB_PORT: 5432

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          POSTGRES_DB: foodgram
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      id: cache-venv  # name for referring later
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt 
    - name: Test with flake8 and django tests
      run: |
        python backend/manage.py check 
        python -m flake8 backend/

